# Generated by Django 3.1.2 on 2021-01-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innoservices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendReviewRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('uuid', models.UUIDField()),
            ],
        ),
    ]
