# Generated by Django 3.1.2 on 2021-01-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innoservices', '0002_sendreviewrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('review', models.TextField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='sendreviewrequest',
            name='uuid_used',
            field=models.BooleanField(default=False),
        ),
    ]
