# Generated by Django 3.1.2 on 2021-01-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innoservices', '0004_clientreview_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreview',
            name='month_year',
            field=models.CharField(default='January 2021', max_length=50),
        ),
    ]
