# Generated by Django 3.1.2 on 2021-01-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innoservices', '0005_clientreview_month_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreview',
            name='upwork_review',
            field=models.BooleanField(default=False),
        ),
    ]
