# Generated by Django 3.1.2 on 2021-10-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innoservices', '0006_clientreview_upwork_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='phone',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='explanation',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
