# Generated by Django 3.1.2 on 2022-12-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innoservices', '0008_auto_20211123_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('PAT', 'Patents'), ('TMK', 'Trademarks'), ('GRE', 'General Research'), ('CAS', 'Case Studies'), ('IPR', 'Intellectual Property')], max_length=3)),
                ('highlight_para', models.TextField(blank=True, null=True)),
                ('highlight_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('content_in_md', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
