# Generated by Django 3.1.2 on 2021-03-08 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('payment_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250)),
                ('client_company', models.CharField(blank=True, max_length=250, null=True)),
                ('client_long_term', models.BooleanField(default=False)),
                ('client_email', models.EmailField(max_length=254)),
                ('project_name', models.CharField(max_length=250)),
                ('project_type', models.CharField(choices=[('PAR', 'Patent Research'), ('VS', 'Validity and Invalidity Search'), ('FTO', 'Freedom to Operate Search'), ('PRR', 'Product Research'), ('LAN', 'Landscape / State of the Art'), ('TS', 'Trademark Search'), ('PD', 'Provisional Draft'), ('FPD', 'Full Patent Draft')], max_length=4)),
                ('project_deadline', models.DateField()),
                ('project_estimated_days', models.IntegerField(default=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expected_revenue', models.FloatField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientAdmin.payment')),
            ],
        ),
    ]
