# Generated by Django 3.1.2 on 2021-03-09 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250)),
                ('client_company', models.CharField(blank=True, max_length=250, null=True)),
                ('client_email', models.EmailField(max_length=254)),
                ('project_name', models.CharField(max_length=250)),
                ('project_type', models.CharField(choices=[('PAR', 'Patent Research'), ('VS', 'Validity and Invalidity Search'), ('FTO', 'Freedom to Operate Search'), ('PRR', 'Product Research'), ('LAN', 'Landscape / State of the Art'), ('TS', 'Trademark Search'), ('PD', 'Provisional Draft'), ('FPD', 'Full Patent Draft')], max_length=4)),
                ('initial_contact_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
