# Generated by Django 3.1.2 on 2021-03-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAdmin', '0002_potentialproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialproject',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
