# Generated by Django 3.1.2 on 2021-03-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAdmin', '0003_auto_20210311_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialproject',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
