# Generated by Django 3.1.2 on 2021-03-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAdmin', '0006_project_is_project_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialproject',
            name='is_client_adandoned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='potentialproject',
            name='is_client_current',
            field=models.BooleanField(default=False),
        ),
    ]
