# Generated by Django 3.1.2 on 2021-03-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAdmin', '0007_auto_20210316_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potentialproject',
            old_name='is_client_adandoned',
            new_name='is_client_abandoned',
        ),
    ]
