# Generated by Django 3.1.2 on 2021-03-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAdmin', '0008_auto_20210316_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250)),
                ('client_company', models.CharField(max_length=250)),
                ('client_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
