# Generated by Django 3.1.2 on 2021-03-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAdmin', '0009_longtermclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialproject',
            name='slug',
            field=models.SlugField(default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=2500),
        ),
    ]
