# Generated by Django 3.1.2 on 2021-11-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAdmin', '0010_auto_20210317_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_invoice_sent',
            field=models.BooleanField(default=False),
        ),
    ]
