# Generated by Django 3.1.2 on 2021-12-11 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAdmin', '0011_project_is_invoice_sent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PotentialProject',
        ),
    ]
