# Generated by Django 3.1.2 on 2021-12-19 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAdmin', '0012_delete_potentialproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendInventionDisclosureQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_company', models.CharField(blank=True, max_length=255, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('uuid', models.UUIDField()),
                ('uuid_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InventionDisclosureQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_company', models.CharField(blank=True, max_length=255, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('MECH', 'Mechanical'), ('CONS', 'Consumer Product'), ('SOFT', 'Software Application'), ('BUSI', 'Business Method'), ('BIOM', 'Biomedical'), ('PHRM', 'Pharmaceutical / Life Sciences / Chemistry'), ('OTHR', 'Other')], max_length=5)),
                ('summary', models.CharField(max_length=3000)),
                ('problem_solved', models.CharField(max_length=3000)),
                ('closest_art', models.CharField(max_length=3000)),
                ('competing_products', models.CharField(max_length=3000)),
                ('advantages', models.CharField(max_length=3000)),
                ('future_improvements', models.CharField(blank=True, max_length=3000, null=True)),
                ('drawings', models.FileField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(max_length=2500)),
                ('existing_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClientAdmin.project')),
            ],
        ),
    ]
