# Generated by Django 3.1.2 on 2022-01-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAdmin', '0014_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='filename',
            field=models.CharField(max_length=3000),
        ),
    ]
