# Generated by Django 3.1.2 on 2022-12-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAdmin', '0015_auto_20220101_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('PAR', 'Patent Research'), ('VS', 'Validity and Invalidity Search'), ('FTO', 'Freedom to Operate Search'), ('PRR', 'Product Research'), ('LAN', 'Landscape / State of the Art'), ('TS', 'Trademark Search'), ('PD', 'Provisional Draft'), ('FPD', 'Full Patent Draft'), ('AC', 'Agreements / Contracts'), ('LR', 'Legal Research'), ('TA', 'Trademark Applications')], max_length=4),
        ),
    ]
