# Generated by Django 3.1.2 on 2020-10-18 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innoaccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnocelfPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('charge_id', models.CharField(max_length=15)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='innocelfcustomer',
            name='global_nda_authorization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='innocelfcustomer',
            name='global_nda_document',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='InnocelfProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=3000)),
                ('date_initiated', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.CharField(max_length=200)),
                ('project_status', models.CharField(choices=[('Pending NDA', 'Pending NDA'), ('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Customer Review', 'Waiting for Customer Review'), ('Completed', 'Completed')], default='Pending NDA', max_length=20)),
                ('report_reviewed', models.BooleanField(default=False)),
                ('review_comments', models.CharField(blank=True, max_length=3000, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_amount', models.FloatField(default=0)),
                ('engagement_letter', models.FileField(blank=True, max_length=500, null=True, upload_to='')),
                ('nda_document', models.FileField(blank=True, max_length=500, null=True, upload_to='')),
                ('reports_for_review', models.FileField(blank=True, max_length=500, null=True, upload_to='')),
                ('final_reports', models.FileField(blank=True, max_length=500, null=True, upload_to='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innoaccounts.innocelfcustomer')),
                ('payment_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innoaccounts.innocelfpayment')),
            ],
        ),
        migrations.AddField(
            model_name='innocelfpayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innoaccounts.innocelfcustomer'),
        ),
        migrations.CreateModel(
            name='InnocelfInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_amount', models.FloatField(default=0)),
                ('payment_status', models.BooleanField(default=False)),
                ('can_download_invoice', models.BooleanField(default=False)),
                ('invoice_file', models.FileField(blank=True, max_length=500, null=True, upload_to='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innoaccounts.innocelfcustomer')),
                ('project_associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innoaccounts.innocelfproject')),
            ],
        ),
    ]
