# Generated by Django 3.1.2 on 2020-10-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innoaccounts', '0002_auto_20201018_0153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InnocelfCustomer',
            new_name='InnocelfClient',
        ),
        migrations.RenameField(
            model_name='innocelfinvoice',
            old_name='customer',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='innocelfpayment',
            old_name='customer',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='innocelfproject',
            old_name='customer',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='innocelfproject',
            name='project_status',
            field=models.CharField(choices=[('Pending NDA', 'Pending NDA'), ('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Client Review', 'Waiting for Client Review'), ('Completed', 'Completed')], default='Pending NDA', max_length=20),
        ),
    ]
