# Generated by Django 3.1.2 on 2020-10-29 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innoaccounts', '0003_auto_20201018_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnocelfStartProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('PS', 'Patentability / Novelty Search'), ('IS', 'Invalidity Search'), ('FOS', 'Freedom to Operate / Clearance Search'), ('PR', 'Product Research'), ('LSA', 'Landscape / State of the Art Search')], max_length=4)),
                ('project_description', models.CharField(max_length=3000)),
                ('project_approved', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innoaccounts.innocelfclient')),
            ],
        ),
    ]
