# Generated by Django 3.1.2 on 2020-10-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innoaccounts', '0004_innocelfstartproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innocelfstartproject',
            name='project_type',
            field=models.CharField(choices=[('PS', 'Patentability / Novelty Search'), ('IS', 'Invalidity Search'), ('FOS', 'Freedom to Operate / Clearance Search'), ('PR', 'Product Research'), ('LSA', 'Landscape / State of the Art Search'), ('OT', 'Other / Not Listed')], max_length=4),
        ),
    ]
